DELIMITER //
DROP FUNCTION IF EXISTS while_100;
CREATE FUNCTION while_100()
  RETURNS INTEGER
BEGIN
  DECLARE result INTEGER DEFAULT 0;
  WHILE result < 100 DO
    SET result=result + 1;
  END WHILE;
  RETURN result;
END//
DELIMITER ;
