version: '2.4'
networks:
  etcd_br0:
    name: etcd_br0
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1

services:
  #新加入的成员和最开始三个成员不在一个service里，但是不影响它们可以组成新的cluster
  etcd4:
    image: quay.io/coreos/etcd:v3.4.7
    container_name: etcd4
    command: etcd -name etcd4 -log-level debug -advertise-client-urls http://172.16.238.14:2379 -listen-client-urls http://172.16.238.14:2379 -listen-peer-urls http://172.16.238.14:2380 -initial-advertise-peer-urls http://172.16.238.14:2380 -initial-cluster-token tkn -initial-cluster "etcd1=http://172.16.238.11:2380,etcd2=http://172.16.238.12:2380,etcd3=http://172.16.238.13:2380,etcd4=http://172.16.238.14:2380" -initial-cluster-state existing
    ports:
      - "32785:2379"
      - "32786:2380"
    networks: 
      etcd_br0:
        ipv4_address: 172.16.238.14
    volumes: 
      - ./etcd4.data:/etcd-data