version: '2.4'
networks:
  etcd_br0:
    name: etcd_br0
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1

services:
  etcd1:
    image: quay.io/coreos/etcd:v3.4.7
    container_name: etcd1
    command: etcd -name etcd1 -log-level debug -advertise-client-urls http://172.16.238.11:2379 -listen-client-urls http://172.16.238.11:2379 -listen-peer-urls http://172.16.238.11:2380 -initial-advertise-peer-urls http://172.16.238.11:2380 -initial-cluster-token tkn -initial-cluster "etcd1=http://172.16.238.11:2380,etcd2=http://172.16.238.12:2380,etcd3=http://172.16.238.13:2380" -initial-cluster-state new
    ports: 
      - "32779:2379"
      - "32780:2380"
    networks: 
      etcd_br0:
        ipv4_address: 172.16.238.11
    volumes: 
      - ./etcd1.data:/etcd-data

  etcd2:
    
    image: quay.io/coreos/etcd:v3.4.7
    container_name: etcd2
    command: etcd -name etcd2 -log-level debug -advertise-client-urls http://172.16.238.12:2379 -listen-client-urls http://172.16.238.12:2379 -listen-peer-urls http://172.16.238.12:2380 -initial-advertise-peer-urls http://172.16.238.12:2380 -initial-cluster-token tkn -initial-cluster "etcd1=http://172.16.238.11:2380,etcd2=http://172.16.238.12:2380,etcd3=http://172.16.238.13:2380" -initial-cluster-state new
    ports: 
      - "32781:2379"
      - "32782:2380"
    networks: 
      etcd_br0:
        ipv4_address: 172.16.238.12
    volumes: 
      - ./etcd2.data:/etcd-data

  etcd3:
    image: quay.io/coreos/etcd:v3.4.7
    container_name: etcd3
    command: etcd -name etcd3 -log-level debug -advertise-client-urls http://172.16.238.13:2379 -listen-client-urls http://172.16.238.13:2379 -listen-peer-urls http://172.16.238.13:2380 -initial-advertise-peer-urls http://172.16.238.13:2380 -initial-cluster-token tkn -initial-cluster "etcd1=http://172.16.238.11:2380,etcd2=http://172.16.238.12:2380,etcd3=http://172.16.238.13:2380" -initial-cluster-state new
    ports:
      - "32783:2379"
      - "32784:2380"
    networks: 
      etcd_br0:
        ipv4_address: 172.16.238.13
    volumes: 
      - ./etcd3.data:/etcd-data